name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please do **not** include auth state, keys, QR codes, or other secrets.

  - type: input
    id: version
    attributes:
      label: pyaileys version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12.2"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 14.4 / Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (redacted)
      description: Paste relevant logs. Redact secrets.
      render: text

